### ISSUE TITLE
ibus usabilty issue 2

### ISSUE THREAD

**Issue by soorajkenoth** [varnamproject/libvarnam-ibus#3]
While using varnam in ibus, all other options will have a number. it will be very easy if we could pick our choice by hitting the number

![missing_ta](https://cloud.githubusercontent.com/assets/3683386/3893607/74c717b8-223c-11e4-9e5d-518d991e24c2.jpg)

**Comment by navaneeth** [comment]
@lonesword I fixed this slightly differently than what you have done. Please pull and test if the behaviour is same.

**Comment by lonesword** [comment]
Merged and tested with my changes. Works fine.
